dist: xenial
os: linux
language: c
env:
  global:
    - NPROC="$(nproc)"
    - JOBS=-j$((1+${NPROC}))
    - SETARCH=
jobs:
  include:
    # Intel, 64-bit, Little-endian
    - name: "amd64 (x86_64) - gcc"
      arch: amd64
      compiler: gcc
    # ARM, 64-bit, Little-endian
    - name: "arm64 (aarch64) - gcc"
      arch: arm64
      compiler: gcc
install: true
before_script:
  - dpkg --print-architecture
  - dpkg --print-foreign-architectures
  - setarch --list
  - echo JOBS=${JOBS} TRAVIS_CPU_ARCH=${TRAVIS_CPU_ARCH} SETARCH=${SETARCH} CC=${CC}
  - $SETARCH uname -a
  - id
  - $CC --version
script:
  - $SETARCH make $JOBS test
branches:
  except:
    # Enable branches except the working in progress branchs "wip/"
    - /^wip\//
